### ISSUE TITLE
支持 SQL Server <-> MySQL

### ISSUE THREAD

**Issue by alswl** [alibaba/yugong#50]
@agapple 
我现在开发了 MySQL <-> SQL Server 的模块，支持 CHECK / FULL 模式。
目前已经运用到生产环境。

但是改动较大，想咨询一下，以什么样的方式提交 PR。

**Comment by agapple** [comment]
你有分支么？我可以提前看看，YAML配置的变化能具体一些么？

**Comment by alswl** [comment]
@agapple 正在申请代码开源中。YAML 配置范例如下：

```yaml
translators:
  record:
    '|BEFORE|':
      - class: com.taobao.yugong.translator.NameStyleDataTranslator
        properties:
          column_case_format_from: UPPER_CAMEL
          column_case_format_to: LOWER_UNDERSCORE
          table_case_format_from: UPPER_CAMEL
          table_case_format_to: LOWER_UNDERSCORE
          schema_to: hj_product
      - class: com.taobao.yugong.translator.ColumnFixDataTranslator
        properties:
          column_replace:
            i_d: id
    ATable:
      - class: com.taobao.yugong.translator.ColumnFixDataTranslator
        properties:
          column_alias:
            bussiness_id:
              - business_id
            is_high_light:
              - is_highlight
      - class: com.taobao.yugong.translator.ColumnFixDataTranslator
        properties:
          json_compress:
            ext_field:
              - mark
              - tags
              - ad_id
```

支持全局更换表名、列名风格；列名字符串替换；多个字段压缩到 JSON 字段内。
